# ==================== NAMESPACES ====================
apiVersion: v1
kind: Namespace
metadata:
  name: backend-workloads
  labels:
    name: backend-workloads
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend-workloads
  labels:
    name: frontend-workloads
---
# ==================== RESOURCE QUOTAS ====================
apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: backend-workloads
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "5"
    pods: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: frontend-quota
  namespace: frontend-workloads
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
---
# ==================== SECRETS ====================
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: backend-workloads
type: Opaque
stringData:
  POSTGRES_USER: capitec_user
  POSTGRES_PASSWORD: capitec_password_2024
  POSTGRES_DB: capitec_users_db
---
# ==================== CONFIGMAPS ====================
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: backend-workloads
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend-workloads
data:
  SPRING_PROFILES_ACTIVE: "production"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/capitec_users_db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend-workloads
data:
  ROOT_URL: "/api"
  BACKEND_URL: "http://backend-service.backend-workloads.svc.cluster.local:8080"
---
# ==================== PERSISTENT VOLUME CLAIM ====================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: backend-workloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
# ==================== DATABASE DEPLOYMENT ====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: backend-workloads
  labels:
    app: postgres
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      tier: database
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      nodeSelector:
        workload-type: capitec
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "capitec"
          effect: "NoSchedule"
        - key: "workload"
          operator: "Equal"
          value: "database"
          effect: "NoSchedule"
        - key: "workload"
          operator: "Equal"
          value: "backend"
          effect: "NoSchedule"
        - key: "workload"
          operator: "Equal"
          value: "frontend"
          effect: "NoSchedule"
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-config
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - capitec_user
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - capitec_user
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
# ==================== DATABASE SERVICE ====================
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: backend-workloads
  labels:
    app: postgres
    tier: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres
    tier: database
---
# ==================== BACKEND DEPLOYMENT ====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend-workloads
  labels:
    app: backend
    tier: application
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
      tier: application
  template:
    metadata:
      labels:
        app: backend
        tier: application
    spec:
      nodeSelector:
        workload-type: capitec
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "database"
          effect: "NoSchedule"
        - key: "dedicated"
          operator: "Equal"
          value: "capitec"
          effect: "NoSchedule"
        - key: "workload"
          operator: "Equal"
          value: "backend"
          effect: "NoSchedule"
        - key: "workload"
          operator: "Equal"
          value: "frontend"
          effect: "NoSchedule"
      containers:
        - name: backend
          image: thapeloseema/capitec-user-service:backend-amd64v1.70
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /users
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /users/all
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /users
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
---
# ==================== BACKEND SERVICE ====================
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-workloads
  labels:
    app: backend
    tier: application
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: backend
    tier: application
---
# ==================== BACKEND HPA ====================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: backend-workloads
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 4
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 2
          periodSeconds: 30
      selectPolicy: Max
---
# ==================== FRONTEND DEPLOYMENT ====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend-workloads
  labels:
    app: frontend
    tier: presentation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      tier: presentation
  template:
    metadata:
      labels:
        app: frontend
        tier: presentation
    spec:
      nodeSelector:
        workload-type: capitec
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "capitec"
          effect: "NoSchedule"
        - key: "workload"
          operator: "Equal"
          value: "database"
          effect: "NoSchedule"
        - key: "workload"
          operator: "Equal"
          value: "backend"
          effect: "NoSchedule"
        - key: "workload"
          operator: "Equal"
          value: "frontend"
          effect: "NoSchedule"
      containers:
        - name: frontend
          image: thapeloseema/capitec-user-service:frontend-amd64v1.0.6
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: frontend-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /home
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /user-list
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /home
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 12
---
# ==================== FRONTEND SERVICE ====================
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend-workloads
  labels:
    app: frontend
    tier: presentation
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: frontend
    tier: presentation
---
# ==================== FRONTEND HPA ====================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: frontend-workloads
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend-deployment
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 2
          periodSeconds: 30
      selectPolicy: Max
---
# ==================== NETWORK POLICIES ====================
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-network-policy
  namespace: backend-workloads
spec:
  podSelector:
    matchLabels:
      app: backend
      tier: application
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: frontend-workloads
          podSelector:
            matchLabels:
              app: frontend
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: postgres
              tier: database
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-network-policy
  namespace: backend-workloads
spec:
  podSelector:
    matchLabels:
      app: postgres
      tier: database
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
              tier: application
      ports:
        - protocol: TCP
          port: 5432
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-network-policy
  namespace: frontend-workloads
spec:
  podSelector:
    matchLabels:
      app: frontend
      tier: presentation
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: backend-workloads
          podSelector:
            matchLabels:
              app: backend
      ports:
        - protocol: TCP
          port: 8080
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
---
# ==================== INGRESS RESOURCES ====================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: frontend-workloads
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: capitec-users.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: backend-workloads
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: capitec-users.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-service
                port:
                  number: 8080