apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app:  app1
    type: backend-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: app1
    type: backend-server