apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app:  app1
    type: front-end
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
  selector:
    app: app1
    type: front-end