apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set
  labels:
    app:  app1
    type: front-end
spec:
  template:
    metadata:
      name: firstpod
      labels:
        app:  app1
        type: front-end
    spec:
      containers:
      - name: nginx-container #list / array
        image: nginx
  replicas: 6
  selector:
    matchLabels:
      type: front-end
    
    